name: Advanced-Transfer
version: '${project.version}'
main: arctic.frosty.advancedtransfer.Advanced_Transfer
api-version: '1.20'
commands:
  transfer:
    description: 'Transfer funds from one player to another.'
    usage: '§4Usage: §c/transfer <player> <amount>'
    aliases:
      - pay
      - tran
  advanced-transfer:
    description: 'Reloading plugin configuration.'
    usage: '§4Usage: §c/advanced-transfer reload'
    aliases:
      - at